modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ohnetstems"
version="0.1.1-Alpha"
displayName="Oh!NetStems"
displayURL=""
credits="MCreator"
authors="CreateCN"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ohnetstems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



