modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ohnetstems"
version="1.0.0"
displayName="Oh!NetStems"
displayURL=""
credits=""
authors="CreateCN, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ohnetstems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



